import{a as L,i as m,S as $}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const S="46859410-d5a1b7b8d3c8579cf11d58e8b",v="https://pixabay.com/api/";async function E(t,r=1,a=15){const s=`${v}?key=${S}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${a}`;try{const e=await L.get(s);return{hits:e.data.hits,totalHits:e.data.totalHits}}catch(e){throw console.error("Error fetching images:",e),e}}const y=()=>{m.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"})},q=()=>{m.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})},x=(t,r)=>{const a=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:n,views:p,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a href="${e}">
          <img src="${s}" alt="${o}" loading="lazy" width="360" height="200" />
        </a>
        <div class="info">
          <p class="info-text"><b>Likes:</b> ${n}</p>
          <p class="info-text"><b>Views:</b> ${p}</p>
          <p class="info-text"><b>Comments:</b> ${b}</p>
          <p class="info-text"><b>Downloads:</b> ${w}</p>
        </div>
      </li>
    `).join("");r.insertAdjacentHTML("beforeend",a)},H=document.querySelector(".search-form"),h=document.querySelector(".gallery-list"),i=document.querySelector(".load-more"),d=15;let l=1,c="",u=0,P=new $(".gallery-list a");i.style.display="none";const O=()=>{const t=document.querySelector(".loader");t&&t.classList.add("show")},f=()=>{const t=document.querySelector(".loader");t&&t.classList.remove("show")};H.addEventListener("submit",async t=>{if(t.preventDefault(),h.innerHTML="",i.style.display="none",c=t.currentTarget.elements.search.value.trim(),l=1,c===""){y();return}await g()});i.addEventListener("click",async()=>{l+=1,await g()});async function g(){O();try{const{hits:t,totalHits:r}=await E(c,l,d);f(),l===1&&(u=r),t.length===0?(y(),i.style.display="none"):(x(t,h),P.refresh(),M(),l*d>=u?(i.style.display="none",q()):i.style.display="block")}catch(t){f(),console.error("Error processing images:",t),iziToast.error({title:"Error",message:"Failed to load images"})}}function M(){const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
